spring.application.name=moviebookingsystem

spring.datasource.url=jdbc:mysql://localhost:3306/movie_booking
spring.datasource.username=root
spring.datasource.password=Alisha@0707
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.flyway.enabled=false
spring.flyway.baseline-on-migrate=false

jwt.secret=movie-booking-system-secret-key-movie-booking-system
jwt.expiration=86400000
